version: '3.3'

volumes:
  #share: # switching to locally hosted mount vs docker volume
  nginx-certs:
  nginx-vhost:
  nginx-html:
  postgis-data:
  postgis-backups:
  geoserver-data:
  shiny-apps:

services:

  nginx-proxy:
    container_name: proxy
    image: jwilder/nginx-proxy
    env_file: .env
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy=true"
    environment:
      DEFAULT_HOST: www.$HOST
      VIRTUAL_HOST_SPECIFIC_PORT: 'true'
      VIRTUAL_PROTO: https
      VIRTUAL_PORT: 443
      DHPARAM_GENERATION: 'false'
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - "./nginx-proxy/nginx.tmpl:/app/nginx.tmpl:ro"
      - "nginx-certs:/etc/nginx/certs:ro"
      - "nginx-vhost:/etc/nginx/vhost.d"
      - "nginx-html:/usr/share/nginx/html"
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
      
  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    container_name: letsencrypt
    environment:
      DEFAULT_EMAIL: 'ben@ecoquants.com' 
    volumes:
     - "/var/run/docker.sock:/var/run/docker.sock:ro"
     - "nginx-certs:/etc/nginx/certs:rw"
     - "nginx-vhost:/etc/nginx/vhost.d"
     - "nginx-html:/usr/share/nginx/html"
    depends_on: 
     - nginx-proxy

  postgis:
    container_name: postgis
    image: postgis/postgis:12-3.0
    environment:
      POSTGRES_DB: gis
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: $PASSWORD
      ALLOW_IP_RANGE: 0.0.0.0/0
    volumes:
      - postgis-data:/var/lib/postgresql
      - /share:/share
    restart: unless-stopped
    healthcheck:
      test: 'exit 0'
    ports:
      - 5432:5432

  postgis-backup:
    container_name: postgis-backup
    image: kartoza/pg-backup:12.0
    volumes:
      - postgis-backups:/backups
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_DBNAME: gis
      POSTGRES_USER: admin
      POSTGRES_PASS: $PASSWORD
      DUMPPREFIX: PG_gis
    restart: unless-stopped
    depends_on:
      - postgis

  geoserver:
    container_name: geoserver
    image: kartoza/geoserver:latest # 2.15.5 on 2020-06-15
    environment:
      VIRTUAL_HOST: "gs.$HOST"
      LETSENCRYPT_HOST: "gs.$HOST"
      USERNAME: admin
      PASS: $PASSWORD
      GEOSERVER_ADMIN_PASSWORD: $PASSWORD
    volumes:
      - geoserver-data:/opt/geoserver/data_dir
      - /share:/share      
    ports:
      - 8080:8080
    restart: unless-stopped
    depends_on:
      - postgis
    healthcheck:
      test: curl --fail -s http://localhost:8080/ || exit 1
      interval: 1m30s
      timeout: 10s
      retries: 3

  rstudio:
    container_name: rstudio
    build: ./rstudio-shiny
    image: bdbest/rstudio:mpatlas
    volumes:
      - /share:/share    
      - shiny-apps:/srv/shiny-server
    restart: unless-stopped
    environment:
      # [Running virtual hosts on different ports of the same container · Issue #560 · jwilder/nginx-proxy](https://github.com/jwilder/nginx-proxy/issues/560)
      VIRTUAL_HOST: "rstudio.$HOST:8787,shiny.$HOST:3838,api.$HOST:8888"
      LETSENCRYPT_HOST: "rstudio.$HOST,shiny.$HOST,api.$HOST"
      ROOT: 'true'
      USER: admin
      PASSWORD: $PASSWORD
      ADD: shiny
    ports:
      - 8787:8787
      - 3838:3838
      - 8888:8888

  nginx:
    container_name: nginx
    build: ./nginx
    volumes:
      - /share:/share    
    restart: unless-stopped
    environment:
      VIRTUAL_HOST: www.$HOST
      LETSENCRYPT_HOST: $HOST,www.$HOST
      LETSENCRYPT_EMAIL: ben@ecoquants.com
    ports:
      - 8088:80
  